version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - springboot-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/productdb?createDataBaseIfNotExist=true&serverTimezone=UTC
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 1234
    networks:
      - springboot-network

volumes:
  db_data:

networks:
  springboot-network:
    driver: bridge
